### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by Aeris1One**
## Problem
- *New PR Template for HQ Apps*

## Solution
- *Applied here*

## PR Status
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Let's wait though for the app to not being Official anymore before merging that one.

**Comment by maniackcrudelis** [comment]
Can be merged

**Comment by Aeris1One** [comment]
Approvals needed to merge :/

**Comment by maniackcrudelis** [comment]
Indeed, I forgot to remove that !

**Pull request merged**
