### PR TITLE
Testing -> Master

### PR DESCRIPTION
**Pull request by Aeris1One**
## Why this PR ?
Make a new release ! (1.1~ynh3)

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Medium decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/hextris_ynh%20PR18/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Even if I don't expect anyone to really try it, when you have a new testing available please announce it on the forum (https://forum.yunohost.org/t/high-quality-app-hextris/10775).
With a changelog to explain what's new, the same way we do for other apps.

Then wait at least one week, to give some time to people to actually try the testing.
If no one has reported any regression after a week, you can ask for actual reviews and it will be merged when it's done.

**Comment by Aeris1One** [comment]
Can I merge now? I need some approvals to do.

**Comment by maniackcrudelis** [comment]
If you don't remind us after a week, you can be sure we're going to forget it ;)
A review from @kay0u would be welcome for the permission stuff.

**Comment by kay0u** [comment]
Can be merged in 3 days :+1:

**Pull request merged**
