### PR TITLE
New stable

### PR DESCRIPTION
**Pull request by Aeris1One**
## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by Aeris1One** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by Aeris1One** [comment]
I'll correct conflicts tomorrow when I'll have access to my PC, may I have some reviews from @YunoHost-Apps/apps-group ?

**Review by yalh76 — APPROVED** [review]
LGTM

**Comment by Aeris1One** [comment]
Well, solving conflicts to a protected branch is really a pain (because I never did that before) so I created another PR where conflicts are solved :)

**Pull request closed without merging**
