### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Global upgrade of the package.*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/hextris_ynh%20PR9/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Proposing to merge that testing promptly after your review...

**Comment by maniackcrudelis** [comment]
LGTM :D ?

**Comment by kay0u** [comment]
Will be merged in 3 days.

**Comment by maniackcrudelis** [comment]
We actually need one more review, I can't review my own code.

**Comment by alexAubin** [comment]
Apparently we got a review ;)

**Comment by kay0u** [comment]
One more O.O

**Comment by JimboJoe** [comment]
Hm... let's say I approve (I'm the PR originator)...? :thinking:

**Pull request merged**
