### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by ericgaspar**
- Small fixes

### CODE REVIEW

**Review by Aeris1One — APPROVED** [review]
LGTM. For real, I'm the least productive on Hextris despite being the official maintainer 😅

**Comment by Aeris1One** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by Aeris1One** [comment]
Do you think it's ready to be merged @ericgaspar ?

**Review by Aeris1One — APPROVED** [review]

**Comment by ericgaspar** [comment]
yes! LGTM 👍

**Pull request merged**
